# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# and https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-pixi

# Required
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "latest"
  jobs:
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    install:
      - pixi install -e docs
    build:
      html:
        # Generate the Sphinx configuration for this Jupyter Book so it builds.
        - pixi run -e docs docs-prepare
        - pixi run -e docs sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

# Optionally build your docs in additional formats such as PDF and ePub
formats: []
